### ISSUE TITLE
Suggestion for more intuitive readme

### ISSUE THREAD

**Issue by yuliroth** [beameio/beame-sdk#2]
hi guys, 

please take a look on my suggestion for more clear README.

https://github.com/beameio/beame-sdk/pull/1

**Comment by zglozman** [comment]
Thank you Yuli, we a few people were working on the readme , thanks for your contribution

**Comment by zglozman** [comment]
Yuli thanks for your feedback, we have revised the readme, as well as added an automated demo. Pls let me know how it works for you
