### ISSUE TITLE
importNonBeameCredentials results badly formatted x509.pem file

### ISSUE THREAD

**Issue by ilyash** [beameio/beame-sdk#4]

**Comment by zglozman** [comment]
this is whats making it look nasty.  We need to fix this, we can do it with the merge of the master. 
  var buffer         = new Buffer(cert.raw, "hex");  
        var certBody       = "-----BEGIN CERTIFICATE-----\r\n";
        certBody += buffer.toString("base64");
        certBody += "-----END CERTIFICATE-----";

**Comment by zenit1** [comment]
Fixed in master
