### ISSUE TITLE
HTTPS servers stalls at [BeameCreds] INFO: Creating edge client for Atom xn...

### ISSUE THREAD

**Issue by melvincarvalho** [beameio/beame-sdk#9]
Previous message:

[BeameServer] INFO: Just created atom with host:xn...

**Comment by melvincarvalho** [comment]
Ah! it ran after about 5 minutes, but then said port in use.  It would be nice to be able to configure the port.  After freeing up the port the chat service ran.

**Comment by zglozman** [comment]
what exactly did you run ? ChatServer?

**Comment by melvincarvalho** [comment]
Yes, I cut and paste from the email.  But this works now.  I just needed to wait a while.  And then stop the process I had running on port 8433.  The chat server worked really well.  Thanks again!

**Comment by zglozman** [comment]
did you try the local interface or the global one ? What are your thoughts for using the beame sdk ?

**Comment by melvincarvalho** [comment]
After installing

     npm install -g beame-sdk

I ran

    beame servers startFirstBeameNode

I was impressed with the beame sdk setup!

**Comment by zglozman** [comment]
Thank u for ur comments. 
It printed two hostnames one is accessible on ur local lan the other is accessible from any device with an Internet connection. Did you try the global hostname as well ?

**Comment by melvincarvalho** [comment]
Yes I tried the global hostname, it worked great! :)
